name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Replace API Key
        env:
          DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
        run: |
          sed -i "s/const DIFY_API_KEY = 'YOUR_API_KEY'/const DIFY_API_KEY = '${{ secrets.DIFY_API_KEY }}'/g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true